- name: Run custom MOTD role
  hosts: all
  become: true
  vars_prompt:
    - name: custom_motd_message
      prompt: "Enter your custom SSH welcome message"
      private: false

  pre_tasks:
    - name: Set and apply default welcome message if input is empty or undefined
      ansible.builtin.set_fact:
        custom_motd_message: "{{ custom_motd_message | default('') | trim | default('Welcome to the server!') }}"

  roles:
    - custom_motd
