name: Lint Ansible Role

on:
  workflow_dispatch:
  push:
    paths:
      - 'roles/**'
      - '.github/workflows/lint.yml'
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install ansible-lint
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint .
